[package]
name = "camber-macros"
version = "0.3.0"
edition.workspace = true
autotests = false
description = "Procedural macros for Camber"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jostled-org/camber"
homepage = "https://github.com/jostled-org/camber"
documentation = "https://docs.rs/camber-macros"
readme = "../../README.md"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
proc-macro-crate = "=3.5.0"
quote = "1"
syn = { version = "3", features = ["full"] }

[[test]]
name = "component_test_macro"
path = "tests/component_test_macro.rs"
